--- 
db_name: castellers.db
debug: false
domain: http://localhost:8000
log_file: castellers.log
smtp_server: "smtp.gmail.com"
smtp_port: "587"
smtp_username: "vilisseranen@gmail.com"
smtp_password: "!sThereAnybody0utThere?"
mail_from: "noreply@clemissa.info"
