# fly.toml file generated for castellers on 2022-07-04T21:52:47-04:00

app = "castellers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
REPLICA_URL="s3://amunt.castellersdemontreal.info-backup/castellers.db"
APP_REDIS_DSN="yul.castellers-redis.internal:6379"
APP_DB_NAME="/data/castellers.db"
APP_SMTP_SERVER="smtp.mailgun.org"
APP_SMTP_PORT="587"
APP_DOMAIN="https://amunt.castellersdemontreal.info"
APP_LOG_LEVEL="debug"
APP_OTEL_ENABLE="true"
OTEL_EXPORTER_OTLP_ENDPOINT="grpc://api.honeycomb.io:443"
OTEL_SERVICE_NAME="castellers"

[build]
  dockerfile = "Dockerfile"

[mounts]
source="castellers_data"
destination="/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
