name: 'Build and test'

on: [workflow_call]

  go-versions:
    name: Lookup go versions
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: arnested/go-version-action@v1
      id: versions
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: go-versions
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    strategy:
      matrix:
        version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
        check-latest: true
    - name: go test
      run: go test -v ./...
