name: 'Check version'

on: [workflow_call]

jobs:
  verify-version:
    name: Verify VERSION has changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/verify-changed-files@v13
        id: verify-changed-version
        with:
          files: |
            VERSION
      - name: Cancel the build if VERSION has not changed
        if: steps.verify-changed-version.outputs.files_changed == 'false'
        uses: andymckay/cancel-action@0.3
