---
name: 'Test and deploy'

on: [push, pull_request]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  verify_version:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/check_version.yml
  build_test:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/build_test.yml
  docker:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/docker.yml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [docker]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --no-cache --config deployment/fly.io/fly.toml