---
name: 'Test and deploy'

on: [push, pull_request]

jobs:
  verify_version:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/check_version.yml
  build_test:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/build_test.yml
  docker:
    needs: [build_test]
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/docker_image.yml
    with:
      tags: |
        dev
        ${{ github.sha }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
