---
name: 'Test and deploy'

on: [push, pull_request]

jobs:
  go-versions:
    name: Lookup go versions
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.head_ref == 'master')
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: arnested/go-version-action@v1
      id: versions
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: go-versions
    if: (github.event_name == 'pull_request' || github.head_ref == 'master')
    strategy:
      matrix:
        version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
        check-latest: true
    - name: go test
      run: go test -v ./...
  docker:
    name: Build docker images
    runs-on: ubuntu-latest
    needs: [test]
    if: (github.event_name == 'pull_request' || github.head_ref == 'master')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REPOSITORY#*/}
          SHORTREF=${GITHUB_SHA::8}
          if [[ ${{github.ref}} != 'refs/heads/master' ]]; then
            VERSION='dev'
            TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF}"
          else
            VERSION=`cat VERSION`
            TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"
          fi

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [docker]
    if: (github.event_name == 'push' && github.head_ref == 'master')
    steps:
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          host: api.amunt.castellersdemontreal.info
          user: ec2-user
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          command: |
            cd /home/ec2-user/castellers/docker-compose/
            git reset --hard
            git checkout master
            git pull --force
            docker-compose pull
            docker-compose up -d