name: 'Check version'

on:
  workflow_call:
    outputs:
      version:
        description: "version specified from VERSION"
        value: ${{ jobs.verify-version.outputs.version }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
      
jobs:
  verify-version:
    name: Verify VERSION has changed
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: read_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: mudlabs/simple-diff@v1.2.0
        id: verify-changed-version
        with:
          path: VERSION
      - name: Cancel the build if VERSION has not changed
        if: !steps.verify-changed-version.outputs.modified
        uses: andymckay/cancel-action@0.3
