name: 'Check version'

on:
  workflow_call:
    outputs:
      version:
        description: "version specified from VERSION"
        value: ${{ jobs.verify-version.outputs.version }}
      
jobs:
  verify-version:
    name: Verify VERSION has changed
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: read_version
        run: echo "version=toto" >> $GITHUB_OUTPUT
      - uses: technote-space/get-diff-action@v6
        id: verify-changed-version
        with:
          FILES: |
            VERSION
      - name: Cancel the build if VERSION has not changed
        if: steps.verify-changed-version.outputs.count == 0
        uses: andymckay/cancel-action@0.3
