name: 'Check version'

on:
  workflow_call:
    outputs:
      version:
        description: "version specified from VERSION"
        value: ${{ jobs.verify-version.outputs.version }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
      
jobs:
  verify-version:
    name: Verify VERSION has changed
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: read_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - id: verify-changed-version
        run: |
          git diff ${{ env.GITHUB_REF_NAME }}..${{ env.GITHUB_BASE_REF }} --exit-code -- VERSION
          echo "version_changed=$?" >> $GITHUB_OUTPUT
      - name: Cancel the build if VERSION has not changed
        if: steps.verify-changed-version.outputs.modified == 0
        uses: andymckay/cancel-action@0.3
      - name: Fail the job if VERSION has not changed
        if: steps.verify-changed-version.outputs.modified == 0
        run: |
          exit 1
