---
name: 'Validate PR before merge'

on:
  pull_request:

jobs:
  verify_version:
    uses: ./.github/workflows/job_check_version.yml
  show_version:
    needs: [verify_version]
    steps:
      - name: show version
        run: |
          echo ${{ needs.verify_version.outputs.version }}
  # test:
  #   uses: ./.github/workflows/job_test.yml
  # docker:
  #   needs: [test]
  #   uses: ./.github/workflows/job_docker_image.yml
  #   with:
  #     tags: |
  #       dev
  #       ${{ needs.verify_version.outputs.version }}
  #       ${{ github.sha }}
  #   secrets:
  #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
